### ISSUE TITLE
Deploy docker service on minikube

### ISSUE THREAD

**Issue by hueyhe** [hueyhe/blog#3]
## Install minikube
> [Installing minikube](https://kubernetes.io/docs/tasks/tools/install-minikube/)

You need to install kubectl & minikube to run your local cluster.

## Prepare your docker image
After finishing your development, you need to build your docker image and push it to a remote repository, such as the docker hub. Here is an example `Dockerfile` of a simple go web service:

```Dockerfile
FROM golang:latest

WORKDIR /usr/local/app

ADD . /usr/local/app
RUN go build -o main .

EXPOSE <port>

CMD ["/usr/local/app/main"]
```

Example docker command:
```bash
$ docker build -t <username>/<service>:<tag> .
```
Now you can run your docker image to see if it works fine:
```bash
$ docker run -p <port>:<port-exposed> <image-name>
```
If everything works fine, you can now push your docker image to the remote repository:
```bash
$ docker push <username>/<service>:<tag>
```
Now you are ready for the next step.

## Setup deployment YAML
When using minikube as your cluster, you need to specify some information of your container and the scalability you want. Create a `deployment.yml` to specify this information.

```yaml
kind: Service
apiVersion: v1
metadata:
  name: <service-name>
spec:
  selector:
    app: <app-name>
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: <inside-port>
      # Port to forward to inside the pod
      targetPort: <container-port>
      # Port accessible outside cluster
      nodePort: <outside-port>
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <deployment-name>
spec:
  replicas: 5
  selector:
    matchLabels:
      app: <app-name>
  template:
    metadata:
      labels:
        app: <app-name>
    spec:
      containers:
        - name: <app-name>
          image: <image-repo>
          ports:
            - containerPort: <container-port>
```

When deploying, minikube will try to pull the docker image you just pushed to the remote.

## Pulling from a private docker image
If you pushed your docker image into a private registry, you need to provide a credential to minikube, since it tries to pull the image from remote.

For detail information please refer to #2
