### ISSUE TITLE
Deploy nginx service on kubernetes with custom configuration

### ISSUE THREAD

**Issue by hueyhe** [hueyhe/blog#5]
> [Connect a Front End to a Back End Using a Service](https://kubernetes.io/docs/tasks/access-application-cluster/connecting-frontend-backend/)

Classic frontend & backend scenario often needs a reverse proxy service. Here we use Nginx as an example.

## Create your configuration file
First, we create our own Nginx configuration file.
```conf
#user  nobody;
worker_processes  1;

events {
  worker_connections  1024;
}

http {
  include       mime.types;
  default_type  application/octet-stream;

  #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
  #                  '$status $body_bytes_sent "$http_referer" '
  #                  '"$http_user_agent" "$http_x_forwarded_for"';

  #access_log  logs/access.log  main;

  sendfile        on;
  #tcp_nopush     on;

  #keepalive_timeout  0;
  keepalive_timeout  65;

  #gzip  on;

  upstream frontend-ssr-service {
    server frontend-ssr-service:8000;
  }

  upstream backend-service {
    server backend-service:9000;
  }

  server {
    listen       80;

    location / {
      proxy_pass http://frontend-ssr-service;
    }

    location ^~ /api/ {
      proxy_pass http://backend-service/api/;
    }
  }
}
```
Using this configuration file, Nginx will proxy all paths under `/api/` to the backend service. Meanwhile, Nginx will proxy all the remaining paths to the frontend ssr service.  To learn more about the matching prefix of location, please refer to [Serving multiple proxy endpoints under location in Nginx](https://serverfault.com/questions/650117/serving-multiple-proxy-endpoints-under-location-in-nginx).

## Build a new Nginx image
We can't use the official Nginx image, because the image doesn't contain our configuration file. Therefore, to include our configuration, we have to build a new image on top of the official image.
```Dockerfile
FROM nginx:stable

COPY nginx.conf /etc/nginx/nginx.conf
```
We don't need `CMD` here, because nginx will start automatically when the container is created. The next thing is to build the image and push it to a remote docker registry.

## Deploy on Kubernetes
Now we have an nginx image with a customized configuration file. We are ready to deploy it to Kubernetes.

```yaml
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 80
      # Port to forward to inside the pod
      targetPort: 80
      # Port accessible outside cluster
      nodePort: 30008
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: <the-image-you-just-pushed>
```
If you are using GKE or AWS, you don't need to specify the node port.

Now it's ready to deploy. If you are using minikube, simply run `kubectl apply -f <deployment-file>`.
