### ISSUE TITLE
Tutorial - How to use commandline to deploy a scalable web application on GKE

### ISSUE THREAD

**Issue by hueyhe** [hueyhe/blog#8]
## Prerequisites
- Web application frontend & backend docker images
- Deployment yaml files for both frontend & backend
- Ingress resource definition yaml file, which defines the network traffic flow
- Google Cloud SDK installed

## Create a cluster
Create a cluster under your Google Cloud Platform project.

## Set up your environment
```bash
$ gcloud config set project [PROJECT_ID]
$ gcloud config set compute/zone [COMPUTE_ENGINE_ZONE]
$ gcloud container clusters get-credentials [CLUSTER]
```
The last command connects the kubectl to the cluster you want to interact with. Now you can use the following command to check whether you have connected with the remote cluster. If connected, you will see both the `Client Version` & `Server version`.
```bash
$ kubectl version
```

## Deploy your web application
Use `kubectl` and your deployment yaml file to create a deployment object on GKE.
```bash
$ kubectl apply -f <deployment-yaml>
```
You can watch the deployment status on the GKE console.

## Deploy the ingress object
The ingress object defines how network traffic flows from external to the inside cluster. Here is an example.
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  backend:
    serviceName: frontend-service
    servicePort: 80
  rules:
    - host: example.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: frontend-service
              servicePort: 80
          - path: /api/*
            backend:
              serviceName: backend-service
              servicePort: 80
```
Just like nginx, you can use ingress as a reverse proxy. After the external IP address is allocated, you can use the IP address to visit your application.
